spring.application.name=dbcine

# Postgres Connection
spring.datasource.url=jdbc:postgresql://litten.myqnapcloud.com:5432/dbcine
spring.datasource.username=perridan
spring.datasource.password=perridan
spring.datasource.driver-class-name=org.postgresql.Driver

# MongoDB Connection (Corrected property name and added DB name)
spring.mongodb.uri=mongodb+srv://danielrechaduran:eXu8HE4SfyRXu2jy@traigger.frqjmys.mongodb.net/
spring.mongodb.database=dbcine
# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optional: Disable strict repository mode if you have issues with multiple DBs
spring.data.mongodb.repositories.type=auto