spring.application.name=dbcine
# Postgres
spring.datasource.url=jdbc:postgresql://litten.myqnapcloud.com:5432/dbcine
# MongoDB
spring.mongodb.uri=mongodb+srv://danielrechaduran:eXu8HE4SfyRXu2jy@traigger.frqjmys.mongodb.net/
spring.datasource.username=perridan
spring.datasource.password=perridan
spring.datasource.driver-class-name= org.postgresql.Driver

# Configuración Hibernate para Postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
