spring.application.name=dbcine
# Postgres
spring.datasource.url=jdbc:postgresql://litten.myqnapcloud.com:5432/dbcine
# MongoDB
spring.data.mongodb.uri=mongodb+srv://danielrechaduran:eXu8HE4SfyRXu2jy@traigger.frqjmys.mongodb.net/
spring.data.mongodb.database=dbcine

# Configuraci�n Hibernate para Postgres
spring.datasource.driver-class-name= org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true